"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { api, ApiClientError } from "@/lib/api";
import { StatusBadge } from "@/components/StatusBadge";

interface RecordDetail { id: string; partner_id: string; customer_id: string | null; rule_id: string | null; period: string; amount: string; status: string; partner_name?: string | null; customer_name?: string | null; rule_rate_pct?: string | null; approved_at: string | null; paid_at: string | null; created_at: string; updated_at: string; }
export default function CommissionDetailPage() {
  const params = useParams<{ id: string }>(); const [record, setRecord] = useState<RecordDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function load() { setLoading(true); try { setRecord(await api.get<RecordDetail>(`/api/v1/commissions/records/${params.id}`)); } catch (err) { setError(err instanceof ApiClientError ? err.message : "Không tải được chi tiết hoa hồng."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [params.id]);
  async function transition(path: string) { setBusy(true); setError(null); try { await api.post(`/api/v1/commissions/records/${params.id}/${path}`); await load(); } catch (err) { setError(err instanceof ApiClientError ? err.message : "Không cập nhật được trạng thái."); } finally { setBusy(false); } }
  if (loading) return <p className="text-sm text-gray-500">Đang tải...</p>; if (!record) return <p className="text-sm text-red-600">{error ?? "Không tìm thấy bản ghi."}</p>;
  return <div><Link href="/commissions" className="text-xs font-medium text-brand-600 hover:underline">← Danh sách hoa hồng</Link><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-lg font-semibold text-gray-900">Chi tiết hoa hồng</h1><p className="mt-1 font-mono text-xs text-gray-500">{record.id}</p></div><StatusBadge status={record.status} /></div>{error && <p className="mt-3 rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<div className="mt-5 grid grid-cols-1 gap-4 rounded-xl border border-gray-200 bg-white p-5 sm:grid-cols-2"><div><p className="text-xs uppercase text-gray-400">Đối tác</p><p className="mt-1 font-medium">{record.partner_name ?? record.partner_id}</p></div><div><p className="text-xs uppercase text-gray-400">Cơ sở khách hàng</p><p className="mt-1">{record.customer_name ?? record.customer_id ?? "Không gán"}</p></div><div><p className="text-xs uppercase text-gray-400">Kỳ tính</p><p className="mt-1">{record.period}</p></div><div><p className="text-xs uppercase text-gray-400">Số tiền</p><p className="mt-1 text-lg font-semibold">{Number(record.amount).toLocaleString("vi-VN")} đ</p></div><div><p className="text-xs uppercase text-gray-400">Quy tắc áp dụng</p><p className="mt-1">{record.rule_id ?? "Không gán"}{record.rule_rate_pct ? ` · ${record.rule_rate_pct}%` : ""}</p></div><div><p className="text-xs uppercase text-gray-400">Thời điểm</p><p className="mt-1 text-sm">Tạo: {new Date(record.created_at).toLocaleString("vi-VN")}<br />Cập nhật: {new Date(record.updated_at).toLocaleString("vi-VN")}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{(record.status === "CALCULATED" || record.status === "PENDING_APPROVAL") && <button disabled={busy} onClick={() => transition("approve")} className="rounded-md bg-brand-600 px-3 py-2 text-sm text-white disabled:opacity-50">Duyệt bản ghi</button>}{record.status === "APPROVED" && <button disabled={busy} onClick={() => transition("mark-paid")} className="rounded-md bg-brand-600 px-3 py-2 text-sm text-white disabled:opacity-50">Ghi nhận đã thanh toán</button>}</div></div>;
}
